name: CI

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.7.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail: true

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
